{{- if .Values.binlog.drainerKafka.create }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "cluster.name" . }}-drainer-kafka
  labels:
    app.kubernetes.io/name: {{ template "chart.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: drainer-kafka
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/managed-by: tidb-operator
      app.kubernetes.io/component: drainer-kafka
  serviceName: {{ template "cluster.name" . }}-drainer-kafka
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8249"
      labels:
        app.kubernetes.io/name: {{ template "chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: tidb-operator
        app.kubernetes.io/component: drainer-kafka
    spec:
      containers:
      - name: drainer
        image: {{ .Values.binlog.drainerKafka.image }}
        imagePullPolicy: {{ .Values.binlog.drainerKafka.imagePullPolicy | default "IfNotPresent" }}
        command:
        - /bin/sh
        - -c
        - |-
{{ tuple "scripts/_start_drainer_kafka.sh.tpl" . | include "helm-toolkit.utils.template" | indent 10 }}
        ports:
        - containerPort: 8249
          name: drainer
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /etc/drainer
      volumes:
      - name: config
        configMap:
          name: {{ template "cluster.name" . }}-drainer-kafka
          items:
          - key: drainer-config
            path: drainer.toml
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.binlog.drainerKafka.storageClassName }}
      resources:
        requests:
          storage: {{ .Values.binlog.drainerKafka.storage }}
{{- end }}
