apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "arbiter.name" . }}-arbiter
  labels:
    app.kubernetes.io/name: {{ template "arbiter.name" . }}
    app.kubernetes.io/component: arbiter
    longroad: arbiter
    app: {{ template "arbiter.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      longroad: arbiter
      app: {{ template "arbiter.name" . }}
  strategy:
    type: Recreate
  template:
    metadata:
      name: {{ template "arbiter.name" . }}
      labels:
        longroad: arbiter
        app: {{ template "arbiter.name" . }}
    spec:
      containers:
        - name: arbiter
          image: {{ .Values.arbiter.image }}
          # command: ["-config", "/etc/arbiter/arbiter.toml"]
          command:
            - /bin/sh
            - -c
            - /arbiter -config /etc/arbiter/arbiter.toml
          volumeMounts:
            - name: config-volume
              mountPath: /etc/arbiter
            - name: data
              mountPath: /data
          env:
          - name: TZ
            value: {{ .Values.timezone }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "arbiterConfig.name" . }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ template "arbiter.name" . }}-arbiter
  # volumeClaimTemplates:
  # - metadata:
  #     name: data
  #   spec:
  #     accessModes: [ "ReadWriteOnce" ]
  #     storageClassName: {{ .Values.arbiter.storageClassName }}
  #     resources:
  #       requests:
  #         storage: {{ .Values.arbiter.storage }}
