timezone: UTC

arbiter:
  name: arbiter
  image: hub.pingcap.net/pingcap/tidb-binlog:v3.0.8

  config:
    # upstream config
    kafkaAddr: "{namespace}-kafka:9092"
    kafkaVersion: "2.0.1"
    topic: "{topic}"

    # downstream config
    dbhost: "{namespace}-targetdb-tidb"
    dbport: 4000
    dbuser: root
    dbpassword: ""
  storageClassName: shared-nvme-disks
  storage: 10Gi
